'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace kunden.ah

    <OptimisticLocking(OptimisticLockingBehavior.LockAll)> _
    <Persistent("Adelholzener.vw_rep_fotos_2_copy_4_bo")> _
    Partial Public Class adelholzener_vw_rep_fotos_2_copy_4_bo
        Inherits XPLiteObject
        Dim fadm_name As String
        <Size(50)> _
        <Persistent("ADM_Name")> _
        Public Property adm_name() As String
            Get
                Return fadm_name
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("adm_name", fadm_name, value)
            End Set
        End Property
        Dim fx1combera_id As Integer
        <Persistent("x1Combera_ID")> _
        Public Property x1combera_id() As Integer
            Get
                Return fx1combera_id
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("x1combera_id", fx1combera_id, value)
            End Set
        End Property
        Dim fx10besuchsdatum As DateTime
        <Persistent("x10Besuchsdatum")> _
        Public Property x10besuchsdatum() As DateTime
            Get
                Return fx10besuchsdatum
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("x10besuchsdatum", fx10besuchsdatum, value)
            End Set
        End Property
        Dim fschluessel As String
        <Persistent("Schluessel")> _
        Public Property schluessel() As String
            Get
                Return fschluessel
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("schluessel", fschluessel, value)
            End Set
        End Property
        Dim fname As String
        <Size(50)> _
        <Persistent("Name")> _
        Public Property name() As String
            Get
                Return fname
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("name", fname, value)
            End Set
        End Property
        Dim fkategorie As String
        <Size(50)> _
        <Persistent("Kategorie")> _
        Public Property kategorie() As String
            Get
                Return fkategorie
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("kategorie", fkategorie, value)
            End Set
        End Property
        Dim fsrcfolder As String
        <Size(66)> _
        Public Property srcfolder() As String
            Get
                Return fsrcfolder
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("srcfolder", fsrcfolder, value)
            End Set
        End Property
        Dim fsrcfile As String
        <Size(117)> _
        Public Property srcfile() As String
            Get
                Return fsrcfile
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("srcfile", fsrcfile, value)
            End Set
        End Property
        Dim fbemerkung As String
        <Size(50)> _
        <Persistent("Bemerkung")> _
        Public Property bemerkung() As String
            Get
                Return fbemerkung
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("bemerkung", fbemerkung, value)
            End Set
        End Property
        Dim fimport_key As String
        <Size(20)> _
        Public Property import_key() As String
            Get
                Return fimport_key
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("import_key", fimport_key, value)
            End Set
        End Property
        Dim fid_kunden_android As Integer
        Public Property id_kunden_android() As Integer
            Get
                Return fid_kunden_android
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("id_kunden_android", fid_kunden_android, value)
            End Set
        End Property
        Dim fidbss_kunden_android As Integer
        Public Property idbss_kunden_android() As Integer
            Get
                Return fidbss_kunden_android
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("idbss_kunden_android", fidbss_kunden_android, value)
            End Set
        End Property
        Dim fj As Integer
        <Persistent("J")> _
        Public Property j() As Integer
            Get
                Return fj
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("j", fj, value)
            End Set
        End Property
        Dim fm As Integer
        <Persistent("M")> _
        Public Property m() As Integer
            Get
                Return fm
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("m", fm, value)
            End Set
        End Property
        Dim ffoto_exported As DateTime
        Public Property foto_exported() As DateTime
            Get
                Return ffoto_exported
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("foto_exported", ffoto_exported, value)
            End Set
        End Property
        Dim fgebiet As String
        <Size(3)> _
        Public Property gebiet() As String
            Get
                Return fgebiet
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("gebiet", fgebiet, value)
            End Set
        End Property
        Dim fid As Integer
        <Key()> _
        <Persistent("ID")> _
        Public Property id() As Integer
            Get
                Return fid
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("id", fid, value)
            End Set
        End Property
        Dim fid_bss As Integer
        <Persistent("ID_BSS")> _
        Public Property id_bss() As Integer
            Get
                Return fid_bss
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("id_bss", fid_bss, value)
            End Set
        End Property
        Dim fdatumintern As DateTime
        Public Property datumintern() As DateTime
            Get
                Return fdatumintern
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("datumintern", fdatumintern, value)
            End Set
        End Property
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
    End Class

End Namespace
